name: "Environment Setup Composite Action"
description: "Sets up Node, installs deps, runs tests, prints env info"

inputs:
  environment:
    description: "Deployment environment"
    required: true
    default: "dev"

runs:
  using: "composite"
  steps:
    - name: Set up Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install
      shell: bash

    - name: Run tests
      run: npm test || echo "Tests failed, but continuing..."
      shell: bash

    - name: Print Environment Info
      run: |
        echo "Running in ${{ inputs.environment }} environment"
        echo "User is ${{ github.actor }}"
        echo "Repository: ${{ github.repository }}"
      shell: bash
