name: Test Environment Setup
on:
    workflow_dispatch:
        inputs:
            environment:
                description: "Deployment environment"
                required: true
                default: "dev"
                type: choice
                options:
                    - dev
                    - test
                    - uat
                    - production
jobs:
    build:
        runs-on: "ubuntu-latest"
        steps:
            - name: checkout
              uses: actions/checkout@v3
            
            - name: Run Environment Setup Action
              uses: ./.github/actions
              with:
                environment: ${{ github.event.inputs.environment }}
