name: Test Environment Setup
on:
    workflow_dispatch:
jobs:
    build:
        runs-on: "ubuntu-latest"
        steps:
            - name: checkout
              uses: actions/checkout@v3
            
            - name: Run Environment Setup Action
              uses: ./.github/actions
              with:
                environment: ${{ github.event.inputs.environment }}
